---
- name: Create the node_exporter group
  ansible.builtin.group:
    name: "{{ node_exporter_system_group }}"
    state: present
    system: true
  when: node_exporter_system_group != "root"

- name: Create the node_exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_system_user }}"
    groups: "{{ node_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: node_exporter_system_user != "root"

- name: Check if systemd_exporter is installed
  ansible.builtin.stat:
    path: "{{node_exporter_install_dir}}/node_exporter"
  register: __systemd_exporter_is_installed
  check_mode: false

- name: debug
  ansible.builtin.debug: 
    msg: "{{__systemd_exporter_is_installed}}"


- name: Install 
  when:
    - __systemd_exporter_is_installed.exists is not defined
  block:

    - name: Download node_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ node_exporter_binary_url }}"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Unpack node_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        remote_src: yes
      check_mode: false

    - name: Propagate node_exporter binaries
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_install_dir }}/node_exporter"
        mode: 0755
        owner: root
        group: root
        remote_src: yes
      notify: restart node_exporter

