---
# defaults file for Prometheus
prometheus_version: 2.27.0
prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus
prometheus_install_dir: /usr/local/bin
prometheus_binary_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/\
                        prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ''
prometheus_metrics_path: "/{{ (prometheus_web_external_url + '/metrics') | regex_replace('^(.*://)?(.*?)/') }}"
prometheus_config_file: 'prometheus.yml.j2'
prometheus_global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_web_config:
  tls_server_config: {}
  http_server_config: {}
  basic_auth_users: {}

prometheus_storage_retention: "30d"
# supported: KB, MB, GB, TB, PB.
prometheus_storage_retention_size: "30MB"

prometheus_targets: {}
  #node:
  # - targets:
  #   - localhost:9100
  #   labels:
  #    env: test

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/*.yml"

