---
#
# Installing kibana
#


# Installing kibana

- name: Install kibana
  ansible.builtin.apt:
   name: kibana
   update_cache: yes
 
- name: Enable service kibana and ensure it is not masked
  ansible.builtin.systemd:
    name: kibana
    enabled: true
    masked: no

- name: Configure kibana
  ansible.builtin.template:
    src: "kibana.yml.j2"
    dest: "{{ kibana_config_file }}/kibana.yml"
    force: true
    owner: kibana
    group: kibana
    mode: 0640


# - name: check 
#   lineinfile: 
#     dest: /etc/kibana/kibana.yml
#     line: "^elasticsearch.serviceAccountToken:"
#   check_mode: yes
#   register: presence
#   #failed_when: presence.changed

- name: Generate token
  ansible.builtin.command: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token --scope kibana
  register: enrollmenttoken

# - name: Push token to var
#   vars:
#     token: '{{ enrollmenttoken.stdout }}'
#   debug: 
#     msg="Elastic password {{ presence }} Save it"

- name: setup kibana with token
  ansible.builtin.command: /usr/share/kibana/bin/kibana-setup -t {{ enrollmenttoken.stdout }}
  notify:
    - restart kibana.service


# - name: Copy file with owner and permissions
#   ansible.builtin.copy:
#     src: "{{ elastic_config_file }}certs/"
#     dest: "{{ kibana_config_file }}certs/"
#     owner: kibana
#     group: kibana
#     mode: '0644'
#     remote_src: yes