---
# tasks file for Prometheus
- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
